### ISSUE TITLE
Failed assertion: line 853 pos 14: 'file != null': is not true.

### ISSUE THREAD

**Issue by HamadBangash353** [zeeshux7860/ImageEditorPro#26]
Exception caught by widgets library =======================================================
The following assertion was thrown building HomePage(dirty, state: _HomePageState#6848e):
'package:flutter/src/painting/image_provider.dart': Failed assertion: line 853 pos 14: 'file != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  HomePage file:///C:/Users/WOL-91%20Hamad/AndroidStudioProjects/ImageEditorPro/example/lib/main.dart:12:12
When the exception was thrown, this was the stack: 
#2      new FileImage (package:flutter/src/painting/image_provider.dart:853:14)
#3      new Image.file (package:flutter/src/widgets/image.dart:470:68)
#4      _HomePageState.build (package:image_editor_pro_example/main.dart:49:28)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4612:27)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
...
====================================================================================================

======== Exception caught by widgets library =======================================================
'package:flutter/src/painting/image_provider.dart': Failed assertion: line 853 pos 14: 'file != null': is not true.
The relevant error-causing widget was: 
  HomePage file:///C:/Users/WOL-91%20Hamad/AndroidStudioProjects/ImageEditorPro/example/lib/main.dart:12:12
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown building HomePage(dirty, state: _HomePageState#6848e):
'package:flutter/src/painting/image_provider.dart': Failed assertion: line 853 pos 14: 'file != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  HomePage file:///C:/Users/WOL-91%20Hamad/AndroidStudioProjects/ImageEditorPro/example/lib/main.dart:12:12
When the exception was thrown, this was the stack: 
#2      new FileImage (package:flutter/src/painting/image_provider.dart:853:14)
#3      new Image.file (package:flutter/src/widgets/image.dart:470:68)
#4      _HomePageState.build (package:image_editor_pro_example/main.dart:49:28)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4612:27)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)

**I clone your project from github and run it on samsung note 8. Immediately red screen appeared and was giving this error.**

**Comment by dernoun** [comment]
@HamadBangash353 
replace this
 `Image.file(_image).toCenter()`
by this 
`_image == null ? Container() : Image.file(_image).toCenter()`
